### ISSUE TITLE
TOC Updater: Switch to doctoc — or use ST3 MarkdownTOC

### ISSUE THREAD

**Issue by tajmone** [tajmone/awesome-interactive-fiction#4]
Hi Yakira,

### Batch Update to Pandoc 2

I've updated the `updatemarkdown.bat` batch script to make it work with the newer pandoc v2 — sorry for the delay, pandoc 2 was released a few monthes ago, but its non-backward compatible changes forced me to revise lots of pandoc dependent projects, and it took me quite a while.

So, the old script doesn't work anymore with pandoc v2.x, nor the new script works with pandoc v1.x. Pandoc 2 implements the new `gfm` format, which is specific to GitHub Flavored Markdown, so it handles it much better than before (still, no support of Task-Lists, except via scripts, but we won't be using Task-Lists here anyhow).

### Dropping gfmtoc for doctoc?

Lately I've considered switching from __[gfmtoc]__ to __doctoc__, another similar tool (still Node.JS):

https://www.npmjs.com/package/doctoc

There are two main reasons why I'd like to do this:

1. I've found some edge cases — usually when special chars are involved — in which gfmtoc fails to render TOC links properly, and as a result some TOCS link don't work.
2. gfmtoc seems to be no longer maintained (last release dates back to 2016), and Node.JS is evolving fast, so my fear is that it might soon have issues with newer versions of Node.JS.

__doctoc__ is very actively maintained, and can handle better special chars in TOC links. Plus, it offers a couple of extra interesting features, and also supports generating markdown TOCs for portals other than GitHub:

- Bitbucket.org
- Nodejs.org
- GitHub.com
- GitLab.com
- Ghost.org 

If it's ok with you, I'd further tweak the batch script to use __doctoc__ instead.

### Sublime Text MarkdownTOC

I personally use Sublime Text 3 for editing markdown docs, and hav installed the __MarkdownTOC__ package which automatically updates the TOC at save-time:

https://packagecontrol.io/packages/MarkdownTOC
https://github.com/naokazuterada/MarkdownTOC

If you happened to also use ST, this might be an even better solution as it doesn't require any scripts and we could do without the batch.

[gfmtoc]: https://www.npmjs.com/package/@hail2u/gfmtoc

**Comment by tajmone** [comment]
__PS__: Unfortunately the new `gfm` pandoc 2 format doesn't support setext-style headers, so the script will convert any underlined headers to Atx style.

I was actually thinking of removing the pandoc invocation part from the script (ie: the "markdown cleanup" by converting to- and from-gfm) since beside converting underlined headers to Atx it also removes reference style links — these might become handy for cross referencing, as the document grows.

I'd keep only the batch part that handles auto-updating the TOC — which is a major hassle in the maintainance of a long doc like this one.

**Comment by yakiradixon** [comment]
Hey there,

I use Sublime Text less and less these days. And I'd prefer not to use any editor-specific tooling, but I haven't allocated time to figuring out what works for me. Please make any tooling changes you find reasonable.

**Comment by tajmone** [comment]
Ok. Then (next time I contribute some contents to the project) I'll change the script to use **doctoc**  instead of **gfmtoc**, so that even contributors who don't use Sublime Text can (could) update the TOC. I'll also remove the pandoc markdown to markdown cleanup, so that reference links can be used in the document (currently the list is growing and in some place reference links would be useful to cross-reference items in the page, and would result in a cleaner source).

I strongly advise you to install **MarkdownTOC** ST package for your own daily usage, it really improves productivity. For markdown editing, I also use the following ST packages, which are really cool:

- https://github.com/SublimeText-Markdown/MarkdownEditing
- https://github.com/revolunet/sublimetext-markdown-preview
- https://packagecontrol.io/packages/Table%20Editor

The **Table Editor** package is a great tool for editing tables in various formats (not only markdown).

**Comment by yakiradixon** [comment]
This is unrelated to the issue but I'll say it here: I would like to transfer ownership of the repository to you, if you'll accept it.

**Comment by tajmone** [comment]
I'll happily take on ownership of the project — and of course, I'll invite you to join as collaborator so you can always contribute to it. I'll add to it a note saying that you were the original creator, of course.

Is the fact that I have a clone of it going to conflict with this operation? ie, two repos with same name?

**Comment by yakiradixon** [comment]
Cool!

I think your fork will cause a conflict, so you'll need to delete it. Let me know when you're ready and I'll send the request.

**Comment by tajmone** [comment]
Deleted!

**Comment by yakiradixon** [comment]
Transfer request sent.

**Comment by tajmone** [comment]
Perfect! It went fine, and you also are still among the contributors, so you can freely contribute whenever you wish.

Thanks. I'll take care of updating the project. I'm on-and-off active with IF, as a player and developer, and during the times I work with IF I'll get a better chance of updating the links.
