### ISSUE TITLE
Add License to Project

### ISSUE THREAD

**Issue by tajmone** [tajmone/awesome-interactive-fiction#5]
@yakiradixon, I was thinking of adding a license to the project. Following the [guidelines of the Awesome proejct], I would go for the [CC0] license (public domain).

Since you're the original creator of this project, I wanted to make sure that this is OK with you.

As you can see, the project is gradually growing and attracting visitors (it's even [mentioned in the homepage of the _Spring Thing_ 2019 competion]). But it really needs to be licensed.

[mentioned in the homepage of the _Spring Thing_ 2019 competion]: https://www.springthing.net/2019/
[CC0]: https://creativecommons.org/publicdomain/zero/1.0/
[guidelines of the Awesome proejct]: https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by yakiradixon** [comment]
Hey! I think a CC0 license is appropriate for this project. 
Thanks for checking in.

**Comment by tajmone** [comment]
Thanks for the approval!

> Hey! I think a CC0 license is appropriate for this project.

Indeed! this is the last of the prerequisites that must be met for adding this repository to original Awesome list of all Awesome lists:

https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

All other requirements were met, so I'll now be able to make a PR for inclusion.
